name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  logos:
    name: "validate logos"
    runs-on: ubuntu-22.04
    strategy:
      node-version: 18
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run validation script
      run: node validate/logos.js

  svgs:
    name: "validate svgs"
    runs-on: ubuntu-22.04
    strategy:
      node-version: 18
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run validation script
      run: node validate/svgs.js
